### ISSUE TITLE
Remove vagrant files

### ISSUE THREAD

**Issue by marcellussiegburg** [lboynton/puppet-rpmfusion#2]
I am a bit surprised to see vagrant code within your version of this module. I think people should be able to use this repo in the manner you did with epel (as git submodule). However it would require them to have a module directory within the directory of the rpmfusion module directory which seems odd to me. You might push users to cluttering up their file system with data for vagrant, even if they are using EPEL / Fedora / CentOS sytems which are non-virtual. I would advice to move vagrant configuration for this module to another git project, if it is required. It seems strange to me to have these files in a rpmfusion module.

**Comment by lboynton** [comment]
I don't think this is a big issue. Vagrant allows me to test that the default configuration works on a local virtual machine, without requiring a virtual machine with Xen/KVM/VMWare etc.

The module directory is a git submodule, which does not exist unless you run `git submodule update --init`.

**Comment by marcellussiegburg** [comment]
Let me try to explain my point further:
- I have seen this project as a puppet module:
  - I thought about a module as defined on pages on puppet labs, i.e. it is structured according to [Module Layout](http://docs.puppetlabs.com/puppet/3/reference/modules_fundamentals.html#module-layout) with a **predictable Structure**
    - Concourning your point that the directory does not exist unless you run the git command: The directory does exist (which is not matching the module layout structure), but you are right if you mean the conetent does not exist.
    - I would think about [Best Practices](http://docs.puppetlabs.com/puppet/3/reference/modules_fundamentals.html#best-practices) and beeing as self-contained as possible to not contain sth. else which does not belong to the module as well
- Maybe this was not intended by the project, in that case:
  - The documentation should be changed and provide the right information of the project, e.g. _the aim of this project is to provide a vagrant setup which automagically provides the rpmfusion repository for a virtual machine_
  - However I think even in that case there should exist two projects
- I guess that your argument is this page [Tests Smoke](http://docs.puppetlabs.com/guides/tests_smoke.html)
  - I agree with the tests directory, which could of course contain many testing files.
  - However the vagrant file is enforcing to test on a "Cent OS 6.3" machine (which should have a special name specified in the vagrant file). Maybe this could be a project of its own: Where multiple modules could be tested on different machines using vagrant.

**Comment by lboynton** [comment]
I agree with all of your points regarding predictable structure and best practices, though I also argue that a best practice is to test your module. Vagrant is how I test the module. This module is not intended to be used solely with Vagrant.

I believe that Puppetlabs themselves encourage this: http://puppetlabs.com/blog/stronger-devops-culture-with-puppet-and-vagrant

FWIW I do plan on adding my CentOS 6.3 machine to Dropbox and referencing it in the Vagrantfile so that anyone else can use it.

**Comment by marcellussiegburg** [comment]
Thank you for the link. I got the point of providing vagrant files within the repository as testing files.

I am not happy with the `modules` directory within this module. Maybe it could be put in the `tests` folder which may not seem to be the right place either, but maybe it is more intuitive than in the root directory?

I am closing this issue, as I now think that the vagrant files can be kept within this module.

**Comment by lboynton** [comment]
Thanks for compromising with me :) I'll try to think about ways to improve the situation in the future.
